services:
  - type: web
    name: ai-email-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY  # you'll replace this directly in Render dashboard
